export const Techniques = {
    EN: [
        {
            img: '../assets/images/cnn.svg',
            header: 'Convolutional Neural Networks',
            text: 'In machine learning, a convolutional neural network (CNN, or ConvNet) is a class of deep, feed-forward artificial neural networks, most commonly applied to analyzing visual imagery.\n' +
            '\n' +
            'CNNs use a variation of multilayer perceptrons designed to require minimal preprocessing.[1] They are also known as shift invariant or space invariant artificial neural networks (SIANN), based on their shared-weights architecture and translation invariance characteristics.',
            timestamp: ''
        },
        {
            img: '',
            header: 'Wavelet transforms',
            text: 'In mathematics, a wavelet series is a representation of a square-integrable (real- or complex-valued) function by a certain orthonormal series generated by a wavelet. This article provides a formal, mathematical definition of an orthonormal wavelet and of the integral wavelet transform.',
            timestamp: ''
        },
        {
            img: '',
            header: 'Arima algorithm',
            text: 'In mathematics, a wavelet series is a representation of a square-integrable (real- or complex-valued) function by a certain orthonormal series generated by a wavelet. This article provides a formal, mathematical definition of an orthonormal wavelet and of the integral wavelet transform.',
            timestamp: ''
        }
    ],
    RU: [
        {
            img: '',
            header: 'Коволюционный нейронные сети',
            text: 'А дль ПьльмМю что-то на русском аывадлыжва  мдвам ямдфыьвмю вям ывм ьвыа мюв бвя юя.ьв ам.бы вам явм .ыбяв амюф ывмжы юбячьсжыьвсы ыжвьсфв мыь дяв мфыбв мжы. s.ldf',
            timestamp: ''
        },
        {
            img: '',
            header: 'Вевлет приобразования',
            text: 'А дль ПьльмМю что-то на русском аывадлыжва  мдвам ямдфыьвмю вям ывм ьвыа мюв бвя юя.ьв ам.бы вам явм .ыбяв амюф ывмжы юбячьсжыьвсы ыжвьсфв мыь дяв мфыбв мжы. s.ldf',
            timestamp: ''
        },
        {
            img: '',
            header: 'Алгоритм Арима',
            text: 'А дль ПьльмМю что-то на русском аывадлыжва  мдвам ямдфыьвмю вям ывм ьвыа мюв бвя юя.ьв ам.бы вам явм .ыбяв амюф ывмжы юбячьсжыьвсы ыжвьсфв мыь дяв мфыбв мжы. s.ldf',
            timestamp: ''
        }
    ]
};
