export const Techniques = {
    EN: [
        {
            img: '../assets/images/Wave4.png',
            header: 'CNN, Wavelets',
            subheader: 'Convolutional Neural Networks and Wavelet transforms',
            text: 'In the frame of trading robot project, we developed a prediction algorithm for 8 steps ahead. The core of the algorithm is a convolutional neural network (CNN), which is trained on pre-prepared images. Each image (see Fig.) is a ROI of a time-frequency wavelet spectrogram with a size of 32x24. At the classifier\'s output we get the probability of the presence of a cyclic channel pattern for the future 8 steps. The algorithm performs scanning of 8 frequency channels in real time simultaniously.',
            timestamp: ''
        },
        {
            img: '',
            header: 'RNN',
            subheader: 'Recurent neural networks',
            text: 'In mathematics, a wavelet series is a representation of a square-integrable (real- or complex-valued) function by a certain orthonormal series generated by a wavelet. This article provides a formal, mathematical definition of an orthonormal wavelet and of the integral wavelet transform.',
            timestamp: ''
        }
    ],
    RU: [
        {
            img: '../assets/images/Wave4.png',
            header: 'CNN, Вейвлеты',
            subheader: 'Конволюционные нейронные сети и вейвлет преобразования',
            text: 'В рамках проекта торгового робота мы разработали алгоритм прогнозирования на 8 тактов вперед. Ядром алгоритма является конволюционная нейронная сеть, которая обучается на предварительно подготовленных изображениях. Каждое изображение (см. рис.) представляет собой область частотно-временной вейвлет-спектрограммы размером 32х24. На выходе класификатора получаем вероятность присутствия циклического паттерна канала на будущих 8-ми отсчетах. Алгоритм осуществляет одновременое сканирование 8ми частотных каналов в реальном масштабе времени.',
            timestamp: ''
        },
        {
            img: '',
            header: 'RNN',
            subheader: 'Рекурентные нейронные сети',
            text: 'А дль ПьльмМю что-то на русском аывадлыжва  мдвам ямдфыьвмю вям ывм ьвыа мюв бвя юя.ьв ам.бы вам явм .ыбяв амюф ывмжы юбячьсжыьвсы ыжвьсфв мыь дяв мфыбв мжы. s.ldf',
            timestamp: ''
        }
    ]
};
